export const currencyOptions = [
    { value: 'USD', label: 'US Dollar (USD)' },
    { value: 'EUR', label: 'Euro (EUR)' },
    { value: 'GBP', label: 'British Pound (GBP)' },
    { value: 'INR', label: 'Indian Rupee (INR)' },
    { value: 'AUD', label: 'Australian Dollar (AUD)' },
    { value: 'CAD', label: 'Canadian Dollar (CAD)' },
    { value: 'CHF', label: 'Swiss Franc (CHF)' },
    { value: 'CNY', label: 'Chinese Yuan (CNY)' },
    { value: 'JPY', label: 'Japanese Yen (JPY)' },
    { value: 'NZD', label: 'New Zealand Dollar (NZD)' },
    { value: 'SGD', label: 'Singapore Dollar (SGD)' },
    { value: 'HKD', label: 'Hong Kong Dollar (HKD)' },
    { value: 'KRW', label: 'South Korean Won (KRW)' },
    { value: 'MYR', label: 'Malaysian Ringgit (MYR)' },
    { value: 'THB', label: 'Thai Baht (THB)' },
    { value: 'ZAR', label: 'South African Rand (ZAR)' },
    { value: 'BRL', label: 'Brazilian Real (BRL)' },
    { value: 'RUB', label: 'Russian Ruble (RUB)' },
    { value: 'MXN', label: 'Mexican Peso (MXN)' },
    { value: 'ARS', label: 'Argentine Peso (ARS)' },
    { value: 'CLP', label: 'Chilean Peso (CLP)' },
    { value: 'COP', label: 'Colombian Peso (COP)' },
    { value: 'PEN', label: 'Peruvian Sol (PEN)' },
    { value: 'VND', label: 'Vietnamese Dong (VND)' },
    { value: 'TRY', label: 'Turkish Lira (TRY)' },
    { value: 'PHP', label: 'Philippine Peso (PHP)' },
    { value: 'EGP', label: 'Egyptian Pound (EGP)' },
    { value: 'SAR', label: 'Saudi Riyal (SAR)' },
    { value: 'AED', label: 'United Arab Emirates Dirham (AED)' },
    { value: 'NGN', label: 'Nigerian Naira (NGN)' },
    { value: 'KES', label: 'Kenyan Shilling (KES)' },
    { value: 'GHS', label: 'Ghanaian Cedi (GHS)' },
    { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
    { value: 'UGX', label: 'Ugandan Shilling (UGX)' },
    { value: 'PKR', label: 'Pakistani Rupee (PKR)' },
    { value: 'BDT', label: 'Bangladeshi Taka (BDT)' },
    { value: 'LKR', label: 'Sri Lankan Rupee (LKR)' },
    { value: 'NPR', label: 'Nepalese Rupee (NPR)' },
    { value: 'IDR', label: 'Indonesian Rupiah (IDR)' },
    { value: 'MAD', label: 'Moroccan Dirham (MAD)' },
    { value: 'DZD', label: 'Algerian Dinar (DZD)' },
    { value: 'TND', label: 'Tunisian Dinar (TND)' },
    { value: 'BHD', label: 'Bahraini Dinar (BHD)' },
    { value: 'OMR', label: 'Omani Rial (OMR)' },
    { value: 'QAR', label: 'Qatari Riyal (QAR)' },
    { value: 'KWD', label: 'Kuwaiti Dinar (KWD)' },
    { value: 'BND', label: 'Brunei Dollar (BND)' },
    { value: 'ILS', label: 'Israeli New Shekel (ILS)' },
    { value: 'IRR', label: 'Iranian Rial (IRR)' },
    { value: 'KZT', label: 'Kazakhstani Tenge (KZT)' },
    { value: 'UZS', label: 'Uzbekistani Som (UZS)' },
    { value: 'TRY', label: 'Turkish Lira (TRY)' },
    { value: 'AZN', label: 'Azerbaijani Manat (AZN)' },
    { value: 'GEL', label: 'Georgian Lari (GEL)' },
    { value: 'AMD', label: 'Armenian Dram (AMD)' },
    { value: 'MKD', label: 'Macedonian Denar (MKD)' },
    { value: 'BGN', label: 'Bulgarian Lev (BGN)' },
    { value: 'HRK', label: 'Croatian Kuna (HRK)' },
    { value: 'RON', label: 'Romanian Leu (RON)' },
    { value: 'HUF', label: 'Hungarian Forint (HUF)' },
    { value: 'CZK', label: 'Czech Koruna (CZK)' },
    { value: 'PLN', label: 'Polish Zloty (PLN)' },
    { value: 'SEK', label: 'Swedish Krona (SEK)' },
    { value: 'NOK', label: 'Norwegian Krone (NOK)' },
    { value: 'DKK', label: 'Danish Krone (DKK)' },
    { value: 'ISK', label: 'Icelandic Krona (ISK)' },
    { value: 'ALL', label: 'Albanian Lek (ALL)' },
    { value: 'RSD', label: 'Serbian Dinar (RSD)' },
    { value: 'KGS', label: 'Kyrgyzstani Som (KGS)' },
    { value: 'MNT', label: 'Mongolian Tugrik (MNT)' },
    { value: 'AFN', label: 'Afghan Afghani (AFN)' },
    { value: 'MVR', label: 'Maldivian Rufiyaa (MVR)' },
    { value: 'LBP', label: 'Lebanese Pound (LBP)' },
    { value: 'SYP', label: 'Syrian Pound (SYP)' },
    { value: 'JOD', label: 'Jordanian Dinar (JOD)' },
    { value: 'YER', label: 'Yemeni Rial (YER)' },
    { value: 'MMK', label: 'Myanmar Kyat (MMK)' },
    { value: 'LAK', label: 'Lao Kip (LAK)' },
    { value: 'KHR', label: 'Cambodian Riel (KHR)' },
    { value: 'BND', label: 'Brunei Dollar (BND)' },
    { value: 'KYD', label: 'Cayman Islands Dollar (KYD)' },
    { value: 'BBD', label: 'Barbadian Dollar (BBD)' },
    { value: 'BSD', label: 'Bahamian Dollar (BSD)' },
    { value: 'BZD', label: 'Belize Dollar (BZD)' },
    { value: 'BMD', label: 'Bermudian Dollar (BMD)' },
    { value: 'BWP', label: 'Botswana Pula (BWP)' },
    { value: 'SBD', label: 'Solomon Islands Dollar (SBD)' },
    { value: 'FJD', label: 'Fijian Dollar (FJD)' },
    { value: 'TOP', label: 'Tongan Paʻanga (TOP)' },
    { value: 'PGK', label: 'Papua New Guinean Kina (PGK)' },
    { value: 'VUV', label: 'Vanuatu Vatu (VUV)' },
    { value: 'MWK', label: 'Malawian Kwacha (MWK)' },
    { value: 'ZMW', label: 'Zambian Kwacha (ZMW)' },
    { value: 'SZL', label: 'Swazi Lilangeni (SZL)' },
    { value: 'MGA', label: 'Malagasy Ariary (MGA)' },
    { value: 'LSL', label: 'Lesotho Loti (LSL)' },
    { value: 'GMD', label: 'Gambian Dalasi (GMD)' },
    { value: 'GNF', label: 'Guinean Franc (GNF)' },
    { value: 'SLL', label: 'Sierra Leonean Leone (SLL)' },
    { value: 'LRD', label: 'Liberian Dollar (LRD)' },
    { value: 'CDF', label: 'Congolese Franc (CDF)' },
    { value: 'XOF', label: 'West African CFA Franc (XOF)' },
    { value: 'XAF', label: 'Central African CFA Franc (XAF)' },
    { value: 'KMF', label: 'Comorian Franc (KMF)' },
    { value: 'BIF', label: 'Burundian Franc (BIF)' },
    { value: 'DJF', label: 'Djiboutian Franc (DJF)' },
    { value: 'ETB', label: 'Ethiopian Birr (ETB)' },
    { value: 'SOS', label: 'Somali Shilling (SOS)' },
    { value: 'SCR', label: 'Seychellois Rupee (SCR)' },
    { value: 'MUR', label: 'Mauritian Rupee (MUR)' },
    { value: 'NAD', label: 'Namibian Dollar (NAD)' },
    { value: 'RWF', label: 'Rwandan Franc (RWF)' },
    { value: 'TZS', label: 'Tanzanian Shilling (TZS)' },
    { value: 'ZWL', label: 'Zimbabwean Dollar (ZWL)' },
    { value: 'BZD', label: 'Belize Dollar (BZD)' },
    { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ)' },
    { value: 'HNL', label: 'Honduran Lempira (HNL)' },
    { value: 'NIO', label: 'Nicaraguan Córdoba (NIO)' },
    { value: 'PAB', label: 'Panamanian Balboa (PAB)' },
    { value: 'PYG', label: 'Paraguayan Guarani (PYG)' },
    { value: 'UYU', label: 'Uruguayan Peso (UYU)' },
    { value: 'BBD', label: 'Barbadian Dollar (BBD)' },
    { value: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)' },
    { value: 'JMD', label: 'Jamaican Dollar (JMD)' },
    { value: 'BBD', label: 'Barbadian Dollar (BBD)' },
    { value: 'BZD', label: 'Belize Dollar (BZD)' },
    { value: 'BMD', label: 'Bermudian Dollar (BMD)' },
    { value: 'FJD', label: 'Fijian Dollar (FJD)' },
    { value: 'GYD', label: 'Guyanese Dollar (GYD)' },
    { value: 'HTG', label: 'Haitian Gourde (HTG)' },
    { value: 'SRD', label: 'Surinamese Dollar (SRD)' },
    { value: 'XCD', label: 'East Caribbean Dollar (XCD)' },
];